services:
  - type: web
    name: project-feedstack
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn feedstack_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://project-feedstack-frontend.onrender.com,http://localhost:3000